### ISSUE TITLE
Logtime requests bug

### ISSUE THREAD

**Issue by eleboucher** [genesixx/coalibot#11]
bc logtime can sometime give different answer based on if the requests finished well.
ex with mbenjell:

0h = no request finished
659h= only the first request (first page) processed.
2200h= supposed result with all the pages processed. 

function in cause https://github.com/genesixx/coalibot/blob/master/src/42_api.js#L112

**Comment by clafoutis42** [comment]
Are you talking about the 42's API Request ?
If so then is the response status always positive ?

It might as well be a timeout from the API that happens on large requests

**Comment by eleboucher** [comment]
Yes.
actually the bug is pretty hard to replicated i get no error on the output

**Comment by clafoutis42** [comment]
Well it sounds like the request has terminated normally. The problem might be from the API and 42's servers. Maybe send a ticket to the dev team ?

**Comment by eleboucher** [comment]
Yep will try to see with the api team
