### ISSUE TITLE
La commande !dobby

### ISSUE THREAD

**Issue by AdamTaguirov** [genesixx/coalibot#15]
Bonjour cher développeur JS (je dégage tout jugement de cette parole).
Suite à l'exécution de la commande !dobby sur le slack de l'école, dans le canal #bots, votre bot codé en JS (je le rappelle) m'a répondu ceci :
"Toi pas maitre Dobby".
Cela a sans doute buggué, puisque je suis sensé avoir les pleins pouvoirs dessus.
Pendant que j'y suis, où est mon droit de commit sur le repo ?
Merci à vous, cher développeur JS.

echo.

**Comment by eleboucher** [comment]
Bonjour cher développeur de serpent,
Je vois en effet que vous n'etes pas sur la liste elitiste des "Maitre de Dobby" bizarement, vous serez ajouter lors de la prochaine mise en production.
Pour ce qui est de votre droit de commit, seule l'equipe de coalibot et de la Elebouch Corp. ® peuvent avoir ces droits.
Cordialement

Erwan Leboucher 
CEO & CTO of Elebouch Corp. ®

**Comment by AdamTaguirov** [comment]
Merci à vous !
Ticket résolu.

**Comment by eleboucher** [comment]
https://github.com/genesixx/coalibot/commit/14766258ae372921ef55690c88ae38850e38b414 Bonjour, le commit a bien ete mis en prod
