### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by eleboucher** [genesixx/coalibot#2]
Avoir des stats des commandes les plus utilise

**Comment by dachristo** [comment]
Tu peux faire comme le fichier reply.json avec en clef la commande et en value le nombre de fois, a chaque commande read, write...

**Comment by eleboucher** [comment]
ouais je voulais le faire sur une base de donnée

**Comment by eleboucher** [comment]
http://coalibot.erwanleboucher.fr/
