### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by lain2006** [genesixx/coalibot#8]
faire un si arise_chickun_arise [arise_chickun_arise@irc.tinyspeck.com] has left #42-the-alliance []
"/invite arise_chickun_arise"

**Comment by ndudnicz** [comment]
guignol

**Comment by eleboucher** [comment]
lain tu es né en 2006 ?

**Comment by lain2006** [comment]
oui

**Comment by eleboucher** [comment]
ah cool

**Comment by lain2006** [comment]
chui 1 g ni

**Comment by eleboucher** [comment]
👎
